name: Build and package extension

on:
  push:
    branches: 
      - webextension
    tags: 
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout project
      uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10      
    - name: Setup node.js
      uses: actions/setup-node@v6
      with: 
        node-version: 24.x
        cache: 'pnpm'
    - name: Install dependencies
      run: |
        pnpm install
    - name: Build for Chrome
      run: |
        pnpm run --filter ./highlight package:ch
        pnpm run --filter ./watch package:ch
    - name: Build for Firefox
      run: |
        pnpm run --filter ./highlight package:ff
        pnpm run --filter ./watch package:ff
    - name: Upload Chrome artifacts
      uses: actions/upload-artifact@v4
      with: 
        name: Chrome
        path: |
          build/chrome/*.zip
    - name: Upload Firefox artifacts
      uses: actions/upload-artifact@v4
      with: 
        name: Firefox
        path: |
          build/firefox/*.zip